engines:
  duplication:
    enabled: true
    exclude_paths:
    - "test/"
    - "src/commands/"
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: "eslint-2"
    checks:
      import/no-unresolved:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
