engines:
  duplication:
    enabled: true
    exclude_paths:
      - 'test/'
      - 'src/commands/'
    config:
      languages:
        - javascript
  eslint:
    enabled: false
  fixme:
    enabled: true
ratings:
  paths:
    - '**.js'
