init: git config --global core.autocrlf input

shallow_clone: true

version: '1.0.{build}'

skip_tags: true

environment:
  matrix:
    - nodejs_version: '6'

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install

test_script: yarn test

build: off

cache:
  - node_modules
  - "%LOCALAPPDATA%/Yarn"
