init: git config --global core.autocrlf input
skip_tags: true

environment:
  nodejs_version: '8'

install:
  - ps: 'Install-Product node $env:node_version'
  - yarn install --frozen-lockfile

test_script: npx mocha --require babel-core/register --recursive

build: off

cache:
  - node_modules
  - '%LOCALAPPDATA%/Yarn'
