init: git config --global core.autocrlf input

shallow_clone: true

version: '1.0.{build}'

skip_tags: true

environment:
  nodejs_version: "6"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --global npx
  - yarn install

test_script: npx mocha --require babel-core/register --recursive

build: off

cache:
 - "%LOCALAPPDATA%\\Yarn"
