module.exports = {
  // eslint-disable-next-line global-require
  ...require('./jest.config'),
  testMatch: ['**/test/integration/**/*.js'],
  setupFiles: ['<rootDir>/testSetupRedis.js'],
  testPathIgnorePatterns: [
    // Tests that relate to `ioredis-mock` only features are commented out
    'test/integration/cluster.js',
    'test/integration/command-transformers.js',
    'test/integration/events.js',
    'test/integration/exec.js',
    'test/integration/keyspace-notifications.js',
    'test/integration/multi.js',
    'test/integration/multiple-mocks.js',
    // @TODO rewrite these tests to no longer use the `data` constructor option
    'test/integration/commands/defineCommand.js',
    'test/integration/commands/hscan.js',
    'test/integration/commands/hscanStream.js',
    'test/integration/commands/linsert.js',
    'test/integration/commands/llen.js',
    'test/integration/commands/lpop.js',
    'test/integration/commands/lpush.js',
    'test/integration/commands/lpushx.js',
    'test/integration/commands/lrange.js',
    'test/integration/commands/lrem.js',
    'test/integration/commands/lset.js',
    'test/integration/commands/ltrim.js',
    'test/integration/commands/psubscribe.js',
    'test/integration/commands/pttl.js',
    'test/integration/commands/publish.js',
    'test/integration/commands/rpop.js',
    'test/integration/commands/rpoplpush.js',
    'test/integration/commands/scanStream.js',
    'test/integration/commands/scard.js',
    'test/integration/commands/sdiff.js',
    'test/integration/commands/sdiffstore.js',
    'test/integration/commands/sinter.js',
    'test/integration/commands/sinterstore.js',
    'test/integration/commands/smembers.js',
    'test/integration/commands/smove.js',
    'test/integration/commands/spop.js',
    'test/integration/commands/sscan.js',
    'test/integration/commands/sscanStream.js',
    'test/integration/commands/subscribe.js',
    'test/integration/commands/ttl.js',
    'test/integration/commands/xadd.js',
    'test/integration/commands/xlen.js',
    'test/integration/commands/xrange.js',
    'test/integration/commands/xread.js',
    'test/integration/commands/xrevrange.js',
    'test/integration/commands/zcard.js',
    'test/integration/commands/zcount.js',
    'test/integration/commands/zevrank.js',
    'test/integration/commands/zincrby.js',
    'test/integration/commands/zinterstore.js',
    'test/integration/commands/zpopmax.js',
    'test/integration/commands/zpopmin.js',
    'test/integration/commands/zrange.js',
    'test/integration/commands/zrangebyscore.js',
    'test/integration/commands/zrank.js',
    'test/integration/commands/zrem.js',
    'test/integration/commands/zremrangebyrank.js',
    'test/integration/commands/zremrangebyscore.js',
    'test/integration/commands/zrevrange.js',
    'test/integration/commands/zrevrangebyscore.js',
    'test/integration/commands/zrevrank.js',
    'test/integration/commands/zscan.js',
    'test/integration/commands/zscanStream.js',
    'test/integration/commands/zscore.js',
  ],
}
