name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read # for checkout

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository == 'stipsan/ioredis-mock'
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
        # temporary until setup-node action comes with npm version that contains oidc setup by default
      - name: Update npm to use trusted publishing (OIDC)
        run: npm install -g npm@latest
      - run: npm ci
      - uses: changesets/action@a45c4d594aa4e2c509dc14a9f2b3b67ba3780d0d # v1.9.0
        with:
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
